before_install: 
  - "gem update --system"
  - "gem --version"
  - "gem install -v 1.10.6 bundler --no-rdoc --no-ri"
  - "bundler --version"
gemfile: 
  - Gemfile
  - Gemfile.jruby
language: ruby
rvm: 
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - jruby-19mode
script: bundle exec rspec
